import Head from 'next/head'
import React from 'react'
import Navbar from './Navbar'

const Layout = ({ title, children }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-page.png" />
      </Head>
      <Navbar />
      <div className="bg-gray-300">
        {children}
      </div>
    </div>
  )
}

export default Layout